import ComponentNavbar from "../components/ComponentNavbar";
import { Providers } from "./providers";
import './globals.css'


export const metadata = {
  title: 'LKC | Sistema GHC',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
      <body>
        <Providers>
          <ComponentNavbar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
